version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: cqrs-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cqrsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: